### ISSUE TITLE
How to change default path for gulpfile.js ?

### ISSUE THREAD

**Issue by medvedevden1s** [GuardRex/vscode-status-bar-tasks#12]
Location of task.json file is ./vscode
My gulpfile.js file location is ./src/folderName/folderName/gulpfile.js

So, the question is, how to set path for gulpfile.js file?

Thanks in advance, 
Denis

**Comment by guardrex** [comment]
I set the extension up so you can put anything into the `arguments` that you want, and it will just add that to the command that is fed to Node's `child_process`.

According to online resources, they did add a `--gulpfile` switch to indicate a `gulpfile.js` someplace outside of the project.

Try this and see if it works ...

``` json
{
    "taskName": "My Command",
    "suppressTaskName": true,
    "args" : ["gulp", "<GULP_COMMAND_HERE>", "--gulpfile", "./src/folderName/folderName/gulpfile.js"]
}
```

**Comment by medvedevden1s** [comment]
Thanks a lot!!! It works
