### ISSUE TITLE
Cancel launched tasks

### ISSUE THREAD

**Issue by ZoolWay** [GuardRex/vscode-status-bar-tasks#13]
Hi!

If I run a task which will run till stopped, like a good old `gulp watch`, how can I stop the task? Will they remain infinitely? Obviously Ctrl+C in the SBT output window does not work ;)

If there is no functionality for that yet, how about marking the status bar entry while running and a second click on it sends a ctrl+C or something else configureable?

**Comment by guardrex** [comment]
Good point, as I've always used the extension myself to just trigger individual, discrete Gulp tasks that run to their end.

The extension isn't really running the command (directly). Commands, like a Gulp task, are executed by Node's `child_process` module behind-the-scenes.

https://github.com/GuardRex/vscode-status-bar-tasks/blob/master/status-bar-tasks/src/extension.ts#L5
https://nodejs.org/api/child_process.html

I believe it creates a shell to run the command via `cmd.exe`. They added a an `options.detached`, which I think is defaulted to `false`; therefore, I think the background processes are shutdown when the parent process is shutdown, which may occur when you close an app or close VS Code.

Have you noticed that background processes are lingering after you close an app? ... or after you close VS Code?

**Comment by ZoolWay** [comment]
Yeah, I myself just did "ending" discrete commands until now.

But as the example showed the `watch` and I wanted to optimize my command line handling, I gave it a try. My serve/watch tasks spawn a webserver so they are not ending.

I was expecting to have that these processes at least terminate when VS Code is closed but that is **not** the case! You have to kill them which is not very nice. Maybe `options.detached` defaults to `true` - but that would surprise me too. Maybe it is because in this case inside the shell another command is spawned which kind of blocks? I use `browser-sync` and default `gulp.watch`.

The documentation also says this:

> By default, the parent will wait for the detached child to exit. To prevent the parent from waiting for a given child, use the child.unref() method. Doing so will cause the parent's event loop to not include the child in its reference count, allowing the parent to exit independently of the child, unless there is an established IPC channel between the child and parent.

I can say when I exit VS Code all code.exe processes are terminated but not the launched gulp tasks (running on node.exe of course).

To enable the plugin handle this I guess you would have to collect all created `ChildProcess` objects here:
https://github.com/GuardRex/vscode-status-bar-tasks/blob/master/status-bar-tasks/src/extension.ts#L82

And then check them periodically or event based if they are still running if you would like to go for some *toggle behaviour*. If not the minimum behavior would be to check them when shutting down and try to kill the child (guess that means https://nodejs.org/api/child_process.html#child_process_child_kill_signal ).

What do you think?

**Comment by guardrex** [comment]
I'm putting in an update today, and I took a second :eyes: look at this. I don't have time myself to implement a feature that would cover this, but I will leave this open and up-for-grabs. This isn't like a paid product, and I have many other professional demands on my time right now (including a big job/contract search for my next gig).

However, I will remove `dotnet watch` from the instructions and call out a special note that if background processes are spawned that they probably will not be shutdown when the project or VS Code is closed.

If anyone wants to take a shot at making it work to optionally kill spawned processes, let me know. Float a plan to me tho before anyone works on it. Whatever is proposed has to dovetail well with the extension's normal functioning.

**Comment by pr-yemibedu** [comment]
Hello,
 So when something is kicked off, do you get back a pid that can be saved? those can be persisted and on various platforms (like tasklist on windows or ps -e on unix/Linux) could help to manage was is still running or what needs to be sent a (taskkill or kill -9) stop command. Just thinking out loud for anyone with time to implement. Thank you. Good day.

**Comment by DrYSG** [comment]
well I like this too.  What about having a button to cancel all spawn child processes of status-bar tasks? That is just keep a list of when you spawn a task like the babel task I have below. Right now, I have to manually find the Node.exe task and then kill it. 


```
{
	"version": "2.0.0",
	"tasks": [
		{
			"command": "${workspaceRoot}/node_modules/.bin/babel.cmd",
			// "isShellCommand": true,
			"args": [
				"src",
				"--out-dir",
				"dist",
				"-w",
				"--source-maps inline"
			],
			"taskName": "Babelizer",
			"suppressTaskName": true,
			"isBuildCommand": true, // make this the F1 > Task: Run Build Task gesture
			"isBackground": true // tell VS Code not wait for this task to finish
		},
```

**Comment by guardrex** [comment]
As silly as this sounds, I'm going to call the current behavior **a feature**. lol :smile: I think having it just use Node's `child_process` module and fire off a completely independent task outside of VSC is fine as a feature for this. I built it originally to run `dotnet` command working with .NET Core console apps and ASP.NET Core web apps, and I don't mind it just running `dotnet` commands however long they take and even if I close down VSC and the task is still running. Thanks tho for the suggestion/recommendation.
