### ISSUE TITLE
Feature request: Exclude tasks from the Status Bar.

### ISSUE THREAD

**Issue by BillDenton** [GuardRex/vscode-status-bar-tasks#15]
I've got a lot of tasks in the tasks.json file, so would like only some of them to appear on the status bar. Would it be possible to mark them for inclusion/exclusion in tasks.json. The excluded commands could be run via Ctrl-Shift-P Run Tasks, so any change would have to be compatible with normal method of running tasks.

**Comment by guardrex** [comment]
I'm going to give this a shot on this update today. I'll ping you back with the outcome ... it should be an easy one-liner to make it do this.

**Comment by guardrex** [comment]
I have this working ... except for one little thing. There might be a schema file for `tasks.json` that results in a warning in the file when a custom property is added.

![capture](https://cloud.githubusercontent.com/assets/1622880/21331355/9a0fb3ec-c607-11e6-9eea-f9e926093a86.PNG)

I'm going to pick back up with the updates when I hear back from the VSC folks: https://github.com/Microsoft/vscode/issues/17566

**Comment by guardrex** [comment]
This is (provisionally*) fixed with latest version in the gallery (v.0.1.2).

provisionally* = I'm still waiting on them to tell me what I can do about the warning on the property that I added to the `tasks.json` file.

The feature works tho, so I'm going to close.

**Comment by BillDenton** [comment]
Thanks. Verified that items marked with '"showInStatusBar": false' do not appear in the status bar. Obviously there is a warning.

**Comment by guardrex** [comment]
They sort answered me, and I almost have a schema applies that will get rid of the warning: https://github.com/Microsoft/vscode/issues/17566
