### ISSUE TITLE
tasks not are runned

### ISSUE THREAD

**Issue by 0xRnato** [GuardRex/vscode-status-bar-tasks#20]
When I click on the task button, this message appears
![image](https://cloud.githubusercontent.com/assets/16787161/24416399/054681d0-13bb-11e7-8a53-d7e042ac26b9.png)
This is my tasks.json file:
```
{
    "version": "0.1.0",
    "showOutput": "always",
    "tasks": [
        {
            "taskName": "Server start",
            "command": "sh",
            "args": ["-c", "sudo /opt/lampp/lampp start"],
            "echoCommand": true,
            "suppressTaskName": true,
            "isShellCommand": true
        },{
            "taskName": "Server stop",
            "command": "sh",
            "args": ["-c", "sudo /opt/lampp/lampp stop"],
            "echoCommand": true,
            "suppressTaskName": true,
            "isShellCommand": true
        },{
            "taskName": "Server restart",
            "command": "sh",
            "args": ["-c", "sudo /opt/lampp/lampp restart"],
            "echoCommand": true,
            "suppressTaskName": true,
            "isShellCommand": true
        },{
            "taskName": "Run gulp",
            "command": "gulp",
            "isBackground": true,
            "echoCommand": true,
            "suppressTaskName": true,
            "isShellCommand": true
        },{
            "taskName": "Run websocket",
            "command": "sh",
            "args": ["-c", "export URL_PORT=3000 && node /opt/lampp/htdocs/websocket/index.js"],
            "echoCommand": true,
            "isShellCommand": true,
            "isBackground": true,
            "suppressTaskName": true
        }
    ]
}
```

**Comment by guardrex** [comment]
I'm a Windows cat, so I'm not familiar with the `sh` shell command or its arguments. Usually when CLI tools don't understand the command, they spit out the usage hints like that. You might want to try organizing them without spaces in the `args`, like this ...
```json
{
    "taskName": "Server restart",
    "command": "sh",
    "args": ["-c", "sudo", "/opt/lampp/lampp", "restart"],
    "echoCommand": true,
    "suppressTaskName": true,
    "isShellCommand": true
}
```

**Comment by 0xRnato** [comment]
Did not work. The way I mounted it and the one that you showed me, works perfectly when I run using ctrl+shift+p, only when I try clicking on the button of status bar,  what gives the problem

**Comment by guardrex** [comment]
The extension uses Node's `child_process` module to run them. I wonder if the `sh` command is even required here. Isn't the `sh` just a shell to run the actual command here, `sudo`? Try this one and see what it does ...
```json
{
    "taskName": "Server restart",
    "command": "sudo",
    "args": ["/opt/lampp/lampp", "restart"],
    "echoCommand": true,
    "suppressTaskName": true,
    "isShellCommand": true
}
```

**Comment by 0xRnato** [comment]
It works!!
But this task doesn't work yet:
```
{
            "taskName": "Run websocket",
            "command": "sh",
            "args": ["-c", "export URL_PORT=3000 && node /opt/lampp/htdocs/websocket/index.js"],
            "echoCommand": true,
            "isShellCommand": true,
            "isBackground": true,
            "suppressTaskName": true
}
```
I tried to follow the same pattern as you said, but for this task did not work

**Comment by guardrex** [comment]
Ok ... progress! :+1:

so you tried it like this ...
```json
{
    "taskName": "Run websocket",
    "command": "export",
    "args": ["URL_PORT=3000 && node /opt/lampp/htdocs/websocket/index.js"],
    "echoCommand": true,
    "isShellCommand": true,
    "isBackground": true,
    "suppressTaskName": true
}
```
I think this is due to the `&&` double command structure. You can combine them both into a single script file, then run the script file with the extension, or you can have two separate tasks ...
```json
{
    "taskName": "Run websocket 1",
    "command": "export",
    "args": ["URL_PORT=3000"],
    "echoCommand": true,
    "isShellCommand": true,
    "isBackground": true,
    "suppressTaskName": true
},
{
    "taskName": "Run websocket 2",
    "command": "node",
    "args": ["/opt/lampp/htdocs/websocket/index.js"],
    "echoCommand": true,
    "isShellCommand": true,
    "isBackground": true,
    "suppressTaskName": true
}
```
I think it breaks when trying to run multiple commands strung together back-to-back.

**Comment by 0xRnato** [comment]
Doesn't work yet :(

**Comment by guardrex** [comment]
Hum ... I'm not sure. The best bet you have for that one is to put the commands into a script file that you know for sure works, then use the extension to run the script file. That was a question from some other devs: What if I have 3 ... or 5 ... or 20 things I want to do? I think a script file should work as long as you don't run into permissions problems running the script.

**Comment by 0xRnato** [comment]
This worked. I was the wrong thing.
```
{
    "taskName": "Run websocket",
    "command": "export",
    "args": ["URL_PORT=3000 && node /opt/lampp/htdocs/websocket/index.js"],
    "echoCommand": true,
    "isShellCommand": true,
    "isBackground": true,
    "suppressTaskName": true
}
```

Thank you so much...

**Comment by 0xRnato** [comment]
Just one more doubt. Is it possible to use 2 background tasks at the same time? I would like to use gulp and a node server at the same time ....

**Comment by guardrex** [comment]
Yes, I think so. Each time you click it immediately launches the task with the Node `child_process` module, so I think they each would run on their own process. There's no way to stop or control them tho ... this extension works best for dedicated one-shot single-fire run and end tasks. It doesn't work well for background tasks that will run forever ... until the machine is shutdown.

**Comment by 0xRnato** [comment]
OK, Thank you o/
