### ISSUE TITLE
showOutput is ignored

### ISSUE THREAD

**Issue by simply-coded** [GuardRex/vscode-status-bar-tasks#25]
"showOutput": "never" 
Does not work. The output window always pops up.

**Comment by guardrex** [comment]
I'll have to research this a bit more. I didn't do anything with `showOutput` with regards to what the extension does. It doesn't read or use the value. The extension just farms out any command to Node's `child_process` module to run it. One would think that `showOutput` would work with the extension OOB as with any other executed command, but idk what's going on with it. I'll try to take a look asap, but it might take a little while ... I'm working FT hours for a major client right now.

**Comment by guardrex** [comment]
They've implemented a new way to control output ...

```json
"presentation": {
    "echo": true,
    "reveal": "always",
    "focus": false,
    "panel": "new"
}
```

I'd love to implement something to take advantage of the new features, but I just don't have the time.
