### ISSUE TITLE
Problem matcher not invoked from plugin?

### ISSUE THREAD

**Issue by Christian-Marx** [GuardRex/vscode-status-bar-tasks#26]
Running tasks using the "task ..." command in VS Code invokes my custom problem matcher, showing the appropriate errors in the problems tab.
However, when running the same task using the "Status Bar Tasks" plugin, the problems tab does not show any errors. I assume this is because the output of the plugin goes to a dedicated "Status Bar Tasks" console? Do I miss any setting?

VS Code Version 1.13.1
Status Bar Tasks Version 0.2.0

**Comment by guardrex** [comment]
That's probably correct. I'd love to look further into it, but I'm slammed these days working FT for Microsoft. I just don't have time to really maintain the extension any more than the critical updates (e.g., I'm going to make it use `label` tonight over the depreciated `taskName`). Thanks tho for asking. Hopefully, the VSC folks will come to their senses and give us all a professionally-built REAL task running toolbar at some point.
