### ISSUE TITLE
Auto-detect tasks using VS Code Tasks 2.0

### ISSUE THREAD

**Issue by aefernandes** [GuardRex/vscode-status-bar-tasks#27]
The VS Code auto-detection updates in [Tasks 2.0](https://code.visualstudio.com/docs/editor/tasks#_task-autodetection) let me run tasks from certain languages without a tasks.json. It would be great to have your status bar icons for those tasks, without having to create a tasks.json. This seems possible in the updated API by registering a task provider.

**Comment by guardrex** [comment]
Possibly ... it's a great suggestion. However, I'm working FT for Microsoft these days, and I just don't have time to implement anything but critical updates. For example, I'm making it use the `label` prop for 2.0.0 *tasks.json* tonight and getting away from the `taskName` prop of 0.1.0/0.2.0. Thanks for raising the issue. Hopefully, VSC folks will wake up and smell the coffee that we need a REAL task running toolbar in VSC.
