### ISSUE TITLE
Possible Integrated Terminal addition?

### ISSUE THREAD

**Issue by mattmogford** [GuardRex/vscode-status-bar-tasks#29]
Hi,
Using windows I've added git bash as my integrated terminal.
But using this extension, it just uses exec and outputs to the output panel.
I think this is using Powershell maybe?

I have changed the extension locally to use the following -
if(useIntegratedTerminal) {
  if(!term) {
    term = vscode.window.createTerminal('Status-Bar-Task ' + cmd);
  }
  term.show();
  term.sendText(cmd);
} else {
  let ls = exec(cmd, { cwd: vscode.workspace.rootPath, maxBuffer: 2048000 });
  ls.stdout.on('data', data => tasksOutputChannel.attachOutput(data));
  ls.stderr.on('data', data => tasksOutputChannel.attachOutput(data));
}

Maybe have this as an option somewhere that can be toggled?

**Comment by mattmogford** [comment]
have made progress on this by adding a useIntegratedTerminal property to the schema
and a check for it in the main code. {updated OP}
If anyone else wants this I can branch it and do it properly.

**Comment by guardrex** [comment]
Yes, I hope you'll do it. I'm swamped working FT for Microsoft. I only have time to perform critical updates (e.g., moving to `label` and away from `taskName` this evening, for example). I hope the VSC folks will properly offer a REAL task running toolbar for VSC. You're welcome under my *Beerware License* (will be added tonight) to do whatever you want with the source code.

**Comment by karbowiak** [comment]
Any chance this could be revived? :)

**Comment by guardrex** [comment]
I'm still swamped with work, and I have a feeling that won't change anytime soon. Someone would need to submit a PR for this that I could then just roll right into the extension. If someone does it, I like the idea of having an option to control this as @mattmogford shows (`useIntegratedTerminal`), which would come in from the workspace options (or default to `false` if not present).

**Comment by mattmogford** [comment]
I could have a look at this. May have a poke around to ight or tomorrow. Will submit a PR if I come up with anything. 
As I Mac at work and Windows at home, I'm using this stuff all the time. Think the last vsc update messed something up again so I have to open an external terminal to do certain things.

**Comment by guardrex** [comment]
I'm going to close because I won't have time to work on the extension further and the current feature set meets the goals of the extension. The basic goal was always to just shell out the task to Node's `child_process` module and let them run with output in the output panel. Anyone who wants this feature can fork and make a version with it using @mattmogford's approach.
