### ISSUE TITLE
Running tests from the status bar result in an error

### ISSUE THREAD

**Issue by Eccenux** [GuardRex/vscode-status-bar-tasks#31]
Seems like the tasks form this status bar work in some different environment.

When I "Run tests" I get and error:

> '.' is not recognized as an internal or external command, operable program or batch file.

Here is my `tasks.json`. Also note that only "Run tests" task was recognized.
```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "gulp",
			"task": "build",
			"problemMatcher": [
				"$eslint-stylish"
			]
		},
		{
			"label": "Run tests",
			"type": "shell",
			"command": "./scripts/test.sh",
			"windows": {
				"command": ".\\scripts\\test.cmd"
			},
			"group": "test",
			"presentation": {
				"reveal": "always",
				"panel": "new"
			}
		},
		{
			"type": "gulp",
			"task": "clean",
			"problemMatcher": [
				"$eslint-stylish"
			]
		}
	]
}
```

**Comment by guardrex** [comment]
I guess it's choking on the dot in `./scripts/test.sh`. Did you try with just `scripts/test.sh` in the `command`?

As for getting them to show up, you need a `label` and a `command` on them. The command should contain the full command, including arguments. For example ...

```
{
    "label": "run gulp"
    "command": "gulp build",
    "type": "gulp",
    "task": "build",
    "problemMatcher": [
        "$eslint-stylish"
    ]
},
```

**Comment by Eccenux** [comment]
I'm running this on Windows 10 so `./scripts/test.sh` should not be used.

**Comment by Eccenux** [comment]
This works (kind of):
```
			"command": ".\\scripts\\test.cmd",
			"linux": {
				"command": "./scripts/test.sh"
			},
```

But it is not run as a test task (ticks are not green).

Also note that above test task is taken from the MS instructions on how to setup a test task:
https://code.visualstudio.com/docs/editor/tasks#_custom-tasks

**Comment by Eccenux** [comment]
I've added a separate `Task` class to make my solution less messy. Would also be possible to add unit tests now.

Strange thing is that I had to change `typings` references to compile and run the plugin in latest VSCode... Seems like there is no `typings` folder in `/node_modules/vscode/`. I can push it as a patch if you have problems running the code.

**Comment by guardrex** [comment]
I'm not really fielding new features of the extension. I encourage devs who need more features or who want to change the extension to fork and create their own version of it. At this point, I'm just waiting on the VSC engineers to *wake up* and put a toolbar in VSC that can run tasks. People keep asking them for it, but they keep declining. I think eventually they will need to take up the feature request.
