### ISSUE TITLE
Increase and/or make configurable maxBuffer

### ISSUE THREAD

**Issue by darkmusic** [GuardRex/vscode-status-bar-tasks#32]
The maxBuffer in exec is currently fixed at 2048000, and if this is exceeded, the process is killed.  As this makes this extension unusable for large builds, this setting needs to be increased and/or made configurable.

**Comment by guardrex** [comment]
Sorry @darkmusic ... I'm not really maintaining the extension with new features. I'm working crazy long hours and don't have time at the moment. I recommend forking the extension and increasing the maxBuffer to meet your needs.
