### ISSUE TITLE
Not work for type: npm

### ISSUE THREAD

**Issue by lukaszpolowczyk** [GuardRex/vscode-status-bar-tasks#34]
```
{
			"label": "npm build",
			"type": "npm",
			"script": "build",
			"problemMatcher": []
		},
		{
			"label": "npm start",
			"type": "npm",
			"script": "start",
			"problemMatcher": []
		}
```

You can see the buttons on the status bar.
When I click, the "Output" panel appears, but nothing happens, the command does not start.

What is wrong? Can this be fixed in an update?

**Comment by guardrex** [comment]
You didn't set up the tasks correctly. See the readme for details or the landing page in the marketplace: https://marketplace.visualstudio.com/items?itemName=GuardRex.status-bar-tasks

**Comment by lukaszpolowczyk** [comment]
It's set up correctly because ... the tasks were generated by vscode based on the package.json file.
These tasks start correctly via Tasks> Run Task ... "npm start". So the task is correct.
Just your extension lacks support for type npm.

Could you introduce support for type npm?

(I know that you can switch to a type shell, etc., but the point is to still do it.)

**Comment by guardrex** [comment]
I can't ... I'm working insane hours right now. Lots of devs are asking me to add lots of new features, and I just can't accommodate the requests. This is why I'm telling everyone to fork the extension and add the feature that they need.

This extension was just a little "for fun" project to help me shell out tasks quickly. I never intended it to become so popular ... I just thought a few dozen devs would find it helpful for basic task running. It really goes to show that they should add a proper task running toolbar to VSC, but they won't listen to the demand for it. https://github.com/Microsoft/vscode/issues/41309
