### ISSUE TITLE
Run in terminal improvement

### ISSUE THREAD

**Issue by bjg2** [GuardRex/vscode-status-bar-tasks#38]
Seems I cannot unclose https://github.com/guardrex/vscode-status-bar-tasks/issues/35, so I'm opening new issue just to get the traction to that one (please take a look at a comment there).

**Comment by guardrex** [comment]
I'm working ~60 hour weeks right now, and I don't have time to maintain the extension. I'm sorry about that, but my job pays the mortgage and puts food on the table, so my paid duties must come first.

IMO the real group who have dropped the ball here is the VSC team. They have steadfastly refused provide a clickable tasks toolbar at every request, and they won't even say why they won't do it.
