### ISSUE TITLE
status-bar-launch

### ISSUE THREAD

**Issue by Alphapage** [GuardRex/vscode-status-bar-tasks#4]
Hello,

Do you plan to implement such a feature to be able to launch the debugger instead of the task ?

I think this would be a great tool and I hope this could help others.

Thank you in advance for your feedback.

**Comment by guardrex** [comment]
@Alphapage They haven't quite firmed up the `dotnet cli` command structure and process for debugging. There was this recent "experimental" approach discussed by MS:

https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/10/experimental-net-core-debugging-in-vs-code/

... and they apparently have it working for executing `dotnet run` and then attaching the debugger to the process. I haven't tried it yet, but I might play with it soon.

I'll leave this open until we know more. As soon as RC2 releases, I'll see how debugging has worked out in VS Code and see what might be possible. Thanks for bringing this to my attention. I'll ping back here when RC2 lands.

**Comment by Alphapage** [comment]
Great news. 
I'm using vscode for nodejs instead of dotnet, but I hope such a tool will help to run quickly a launch.json config.

**Comment by guardrex** [comment]
As long as the command can be executed by Node's `child_process` module,
the current extension should work. That's the module it's using to run the
`dotnet` commands you see in the sample `Tasks.json` file.

I'll keep an eye on the debugging bits and see if I need to add something
to the extension at RC2.

**Comment by guardrex** [comment]
I have an update coming up in a few weeks. I'll see if I can make it do this at the same time and have a bool setting to add the command to the status bar. It will depend on if their API has a command that will trigger the debugger. I'll find out and report back when I get to the next update.

**Comment by guardrex** [comment]
They've added a debugger launch now to the status bar, so we're covered on this request now.
