### ISSUE TITLE
always opening "output" panel

### ISSUE THREAD

**Issue by mtiziano** [GuardRex/vscode-status-bar-tasks#40]
every time i run this task, it opens "output" panel, even with **"presentation": { "reveal" : "never" }**

    "version": "2.0.0",
    "tasks": [
        {
            "label": "$(sync) shake",
            "command": "%ANDROID_HOME%\\platform-tools\\adb shell input keyevent 82",
            "presentation": {
                "reveal": "never"
            }
        },
    ]

**Comment by chiboreache** [comment]
That extremely, not **EXTREMELY** annoying!

**Comment by guardrex** [comment]
Sorry ... closing. I'm so insanely busy that I can no longer maintain it. I'll leave it archived in case someone wants to make their own extension out of it.
