### ISSUE TITLE
The variable ${workspaceRoot} was deprecated

### ISSUE THREAD

**Issue by XianwuLin** [GuardRex/vscode-status-bar-tasks#42]
https://code.visualstudio.com/docs/editor/variables-reference#_common-questions

Q: Why isn't ${workspaceRoot} documented?

A: The variable ${workspaceRoot} was deprecated in favor of ${workspaceFolder} to better align with Multi-root Workspace support.

**Comment by guardrex** [comment]
Sorry ... closing. I'm so insanely busy that I can no longer maintain it. I'll leave it archived in case someone wants to make their own extension out of it.
