### ISSUE TITLE
Refresh status bar when tasks.json is saved

### ISSUE THREAD

**Issue by Alphapage** [GuardRex/vscode-status-bar-tasks#5]
Hello,

I think this could be possible to detect when tasks.json is modified, then refresh the status bar:

```
context.subscriptions.push(vscode.workspace.onDidSaveTextDocument((textDocument: vscode.TextDocument) => {

                }));
```

From there, I don't know if you need to use a command to 'Reload Window' or if you can refresh the status bar directly which should be better.
Need to investigate more.

Thanks in advance for your feedback.

**Comment by guardrex** [comment]
@Alphapage I'm going to look into this later today. I can possibly knock out two birds with one stone: There is also a request for variable substitution that would be a nice feature add to the extension. I'll ping back later.

**Comment by guardrex** [comment]
@Alphapage I didn't get to this today, but I think I'll have time Thursday evening (or sometime this weekend at the latest). I'll ping back as soon as I can get to it.

**Comment by guardrex** [comment]
@Alphapage I attempted this today, but it didn't work. I need to play with it a little more. I was hoping this would work inside of the `activate()`, but it's throwing an exception about the ":" (colon) there in the paramters.

``` typescript
var cmd = vscode.commands.registerCommand('extension.executeOnSave', () => {
    var onSave = vscode.workspace.onDidSaveTextDocument((e: vscode.TextDocument) => {
        // will attempt reloading the tasks into the status bar here
    });
    context.subscriptions.push(onSave);
});
context.subscriptions.push(cmd);
```

I'll try to get back and take another look at this sometime this week.

**Comment by guardrex** [comment]
@Alphapage :tada: Got IT! :tada: :smile: Version with this feature is 0.0.9 and it's in the gallery now.

If it doesn't show up as an "outdated extension" in your VS Code when you F1, then (1) delete it, (2) restart VS Code, (3) install 0.0.9.

I'll wait for you to confirm that it works before closing the issue. All you have to do is make an update to your `tasks.json` file and save the file. The status bar tasks should update immediately to reflect the changes you made to the file.

**Comment by Alphapage** [comment]
I've just tested and it seems to work. This is a great new feature. Thank you
