### ISSUE TITLE
Support for auto-detected gulp tasks

### ISSUE THREAD

**Issue by ZoolWay** [GuardRex/vscode-status-bar-tasks#7]
Hi,

I can run gulp tasks with the task runner in VS code with a `tasks.json` like this:

```
{
    "version": "0.1.0",
    "command": "gulp",
    "isShellCommand": true,
    "tasks": []
}
```

Note that there are no tasks mentioned, they are auto-detected from the gulpfile. Would be great if this extension could offer that too!

**Comment by guardrex** [comment]
That's a good feature request, but I'm extremely time-limited right now.

It would have to be opt-in with a VS Code setting. Many devs wouldn't want a feature like this turned on by default.
1. Many devs either have a small subset of commands that they keep in the status bar ... not everything in their gulpfile (or even anything from their gulpfile at all), and
2. Many devs organize their gulpfile with lower-level tasks (to keep their gulpfile well organized) but have higher-level tasks that trigger several lower-level tasks and those are the ones they actually use ... I could never know that from just reading the file and shooting the tasks into the status bar which tasks they are actually using.

Therefore, this would have to be an opt-in by VS Code setting feature.

The other prob I have is just time. I'm working daily trying to get a few large apps ported to .NET Core, and stopping for a half-day to set this up would cut into my dev time on those projects.

I'll leave this open and see if I get some free time in the coming weeks to see if I can implement it fairly quickly. The only thing that I think would take any significant time (the thing I don't know about) is how to parse the VS Code settings. I would need to parse the project settings file (if it exists), the user settings file, and the workspace settings file. I don't know anything about how that's done.

**Comment by guardrex** [comment]
I'm planning an update for the extension in a couple of weeks. That will include an attempt to setup a custom setting for controlling the default VSC behavior of adding the top-level command and arguments to each task. I'll see if I can add a custom bool setting to make it read in the gulpfile commands, too. It will take a few weeks to get there, but I'll post back here the result of my efforts.

**Comment by guardrex** [comment]
Ha! ... "in a couple of weeks." What was I thinking?? lol I've been putting in crazy hours, and the :turkey: Day break is the first break I've had to catch my breath.

However, I simply won't be able to implement this one. I'm only going to deal with the most important issues that pertain to keeping the extension working with VS Code (e.g., moving to the `label` prop in *tasks.json*).
